export default {
	ADD_EXPENSE:"ADD_EXPENSE",
	EDIT_EXPENSE:"EDIT_EXPENSE",
	REMOVE_EXPENSE:"REMOVE_EXPENSE",
	SET_TEXT_FILTER:"SET_TEXT_FILTER",
	SET_START_DATE:"SET_START_DATE",
	SET_END_DATE:"SET_END_DATE",
	SORT_BY_DATE:"SORT_BY_DATE",
	SORT_BY_AMT:"SORT_BY_AMT",
	SORT_BY_DESC:"SORT_BY_DESC",
};